// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RazorPagesChessPlayersExample.Migrations
{
    [DbContext(typeof(RazorPagesChessPlayersExampleContext))]
    [Migration("20220531153009_numberOfTournamentVictories")]
    partial class numberOfTournamentVictories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("RazorPagesChessPlayersExample.Models.ChessPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfTitleAcquisition")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTournamentVictories")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ChessPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
